services:
  api:
    platform: linux/amd64
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 22.13.0
    ports:
      - "3000:3000"
      - "9223:9223"
    volumes:
      - ./.cache:/app/.cache
    networks:
      - steel-network
     environment:
      - STEEL_HOST=${STEEL_HOST:-0.0.0.0}
      - STEEL_DOMAIN=${STEEL_DOMAIN:-localhost}
      - STEEL_PORT=${STEEL_PORT:-3000}
      - STEEL_CDP_REDIRECT_PORT=${STEEL_CDP_REDIRECT_PORT:-9222}
      - STEEL_PROXY_URL=${STEEL_PROXY_URL}
      - STEEL_DEFAULT_HEADERS=${STEEL_DEFAULT_HEADERS:-{}}
      - STEEL_KILL_TIMEOUT=${STEEL_KILL_TIMEOUT:-25}

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://api:3000}
        VITE_WS_URL: ${VITE_WS_URL:-ws://api:3000}
        VITE_OPENAPI_URL: ${VITE_OPENAPI_URL:-http://api:3000/documentation/json}
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://api:3000}
      - VITE_WS_URL=${VITE_WS_URL:-ws://api:3000}
      - VITE_OPENAPI_URL=${VITE_OPENAPI_URL:-http://api:3000/documentation/json}
    depends_on:
      - api
    networks:
      - steel-network

networks:
  steel-network:
    driver: bridge